repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^(tests/|examples/|dependabot_check/)
    -   id: end-of-file-fixer
        exclude: ^(tests/|examples/|dependabot_check/)
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
        exclude: ^(tests/|examples/|dependabot_check/)

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^(tests/|examples/|dependabot_check/)

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        exclude: ^(tests/|examples/|dependabot_check/)

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^(tests/|examples/|dependabot_check/)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-requests]
        exclude: ^(tests/|venv/|build/|dist/|setup.py)

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
        args: ["-r", "src/"]
        exclude: ^(tests/|venv/|build/|dist/)