# OSSF Scorecard configuration
# https://github.com/ossf/allstar/blob/main/pkg/policies/scorecard/README.md

optConfig:
  optOutStrategy: false  # Set to false to opt-in

policy:
  # Minimum acceptable OSSF Scorecard score
  minScore: 7.0
  
  # Checks that must pass
  requiredChecks:
    - Branch-Protection
    - Code-Review
    - Dangerous-Workflow
    - Maintained
    - Security-Policy
    - Vulnerabilities
  
  # Specify a threshold for specific checks
  checkScoreThresholds:
    Branch-Protection: 7.0
    Dangerous-Workflow: 8.0
    Maintained: 7.0
    
action:
  # Create an issue when non-compliant
  issue: true
  
  # Add labels to created issues
  issueLabels:
    - security
    - allstar