# Security Policy configuration
# https://github.com/ossf/allstar/blob/main/pkg/policies/security/README.md

optConfig:
  optOutStrategy: false  # Set to false to opt-in

policy:
  # Enforces presence of a SECURITY.md file (we already have this)
  requireSecurityPolicy: true
  
  # Specify alternates names and locations
  securityPolicyPaths:
    - SECURITY.md
    - docs/security/SECURITY.md
    - .github/SECURITY.md
    
  # Specify minimum content length to be valid
  securityPolicyMinimumLength: 100

action:
  # Create an issue when non-compliant
  issue: true
  
  # Add labels to created issues
  issueLabels:
    - security
    - allstar